spring:
  session:
    store-type: redis
  datasource:
    password: butcher
    url: jdbc:postgresql://postgresql:5432/butcher
    username: butcher
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
