app:
  socket:
    io:
      hostname: localhost
spring:
  redis:
    host: localhost
    password:
  datasource:
    url: jdbc:postgresql://localhost:5432/butcher
    username: butcher
    password: butcher
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
