server:
  port: 8080
app:
  socket:
    io:
      hostname: localhost
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/butcher
    username: butcher
    password: butcher
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    url: jdbc:postgresql://localhost:5432/butcher
    user: butcher
    password: butcher
