server:
  port: ${SERVER_PORT}
spring:
  session:
    store-type: redis
  redis:
    url: ${APPL_REDIS_URL}
    ssl: ${APPL_REDIS_SSL}
  datasource:
    url: ${APPL_DATASOURCE_JDBC_URL}
    username: ${APPL_DATASOURCE_USERNAME}
    password: ${APPL_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
