spring:
  session:
    store-type: redis
  redis:
    host: ${APPL_REDIS_HOST}
    password: ${APPL_REDIS_PASSWORD}
  datasource:
    url: ${APP_DATASOURCE_JDBC_URL}
    username: ${APP_DATASOURCE_USERNAME}
    password: ${APP_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
