apiVersion: v1
kind: Service
metadata:
    name: "butchercluster-80ed"
    labels:
        app: "butchercluster-80ed"
spec:
    type: LoadBalancer
    ports:
    - port: 80
      targetPort: 80
      protocol: TCP
      name: http
    selector:
        app: "butchercluster-80ed"