spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/halbzit
    username: halbzit
    password: halbzit
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
