name: Build and test backend

on:
  [push]

jobs:
  build-and-test:
    name: Build and test
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: butcher
          POSTGRES_PASSWORD: butcher
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10
    steps:
      - uses: actions/checkout@v2

      - name: Set up Java version
        uses: actions/setup-java@v1
        with:
          java-version: '11'

      - name: Build with Maven
        run: |
          cd ./backend
          mvn -B package --file pom.xml
