# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy WAR app to Azure Web App - butcher-backend

on:
  push:
    branches:
      - canary

env:
  AZURE_APP_NAME: butcher-backend
  AZURE_WAR_PACKAGE_PATH: './backend/target/butcher-back.war'
  JAVA_VERSION: 11

jobs:
  build-and-deploy:
    name: Build and Deploy
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:11-alpine
        env:
          POSTGRES_USER: butcher
          POSTGRES_PASSWORD: butcher
        options: >-
          --health-cmd pg_isready
          --health-interval 3s
          --health-timeout 2s
          --health-retries 10

    steps:
    - uses: actions/checkout@v2

    - name: Set up Java version
      uses: actions/setup-java@v1
      with:
        java-version: ${{ env.JAVA_VERSION }}

    - name: Build with Maven
      run: |
        cd ./backend
        mvn -B package --file pom.xml

    - name: Deploy to Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: ${{ env.AZURE_APP_NAME }}
        slot-name: 'production'
        publish-profile: ${{ secrets.AzureAppService_PublishProfile_845fadd97536464b9fb70e57892a128f }}
        package: '${{ env.AZURE_WAR_PACKAGE_PATH }}'